### ISSUE TITLE
does not deploy on win10 maya2017/18

### ISSUE THREAD

**Issue by krz9000** [Ziriax/Maya2glTF#23] opened 2018-05-28 18:15 UTC
Copying "D:\Users\xxx\Desktop\Maya2glTF-master\maya\\maya" to "D:\Users\xxx\Documents\maya"...
File not found - maya
0 File(s) copied
Done. Press ENTER to exit.
Press any key to continue . . .

**Comment by Ziriax** [comment] 2018-05-29 08:22
I can't reproduce this.

This can only happen when your `Documents` folder doesn't have a `maya` sub-folder, but that sub-folder should exist when you installed `maya`. 

I could of course patch my installer script so that it creates a `maya` sub-folder, but since the sub-folder didn't exist, most likely Maya will not pick it up anyway.

Could you show me the content of your `D:\Users\xxx\Documents\maya` (=`%userprofile%\Documents\maya`) folder? (only those entries you want to share). You can do this by pressing `WindowsKey+R`, and then pasting

```
cmd /k dir /ad /b "%userprofile%\Documents"
```

Press okay, select the text in the console window with the mouse, press `ENTER`, and then paste the output here.

Could you then run Maya, open the script window, and paste and execute following script code:
```
getenv("MAYA_SCRIPT_PATH")
```

Please copy/paste the output of this.

Thanks!
Peter

**Comment by krz9000** [comment] 2018-05-29 08:34
oh i def have a maya folder with several mayversion subfolders inside. 

Copying "D:\Users\xxx\Desktop\Maya2glTF-master\maya\maya" to "D:\Users\xxx\Documents\maya"...
....between the maya\maya are actually 2 \. this website is removing one of them...maybe thats causing a issue?

**Comment by Ziriax** [comment] 2018-05-29 08:53
Mmm. 

How did you get this `D:\Users\xxx\Desktop\Maya2glTF-master\maya\maya` directory structure? That is strange, my directory after unpacking the ZIP archive looks like:

```
C:\Users\Peter\Desktop\Maya2glTF\deploy.bat
C:\Users\Peter\Desktop\Maya2glTF\Maya
C:\Users\Peter\Desktop\Maya2glTF\Maya\2017
C:\Users\Peter\Desktop\Maya2glTF\Maya\2018
C:\Users\Peter\Desktop\Maya2glTF\Maya\Maya2glTF
C:\Users\Peter\Desktop\Maya2glTF\Maya\2017\plug-ins
C:\Users\Peter\Desktop\Maya2glTF\Maya\2017\scripts
C:\Users\Peter\Desktop\Maya2glTF\Maya\2017\plug-ins\maya2glTF.mll
C:\Users\Peter\Desktop\Maya2glTF\Maya\2017\scripts\maya2glTF_assignPbrShader.mel
C:\Users\Peter\Desktop\Maya2glTF\Maya\2017\scripts\maya2glTF_UI.mel
C:\Users\Peter\Desktop\Maya2glTF\Maya\2018\plug-ins
C:\Users\Peter\Desktop\Maya2glTF\Maya\2018\scripts
C:\Users\Peter\Desktop\Maya2glTF\Maya\2018\plug-ins\maya2glTF.mll
C:\Users\Peter\Desktop\Maya2glTF\Maya\2018\scripts\maya2glTF_assignPbrShader.mel
C:\Users\Peter\Desktop\Maya2glTF\Maya\2018\scripts\maya2glTF_UI.mel
C:\Users\Peter\Desktop\Maya2glTF\Maya\Maya2glTF\PBR
C:\Users\Peter\Desktop\Maya2glTF\Maya\Maya2glTF\PBR\images
C:\Users\Peter\Desktop\Maya2glTF\Maya\Maya2glTF\PBR\shaders
C:\Users\Peter\Desktop\Maya2glTF\Maya\Maya2glTF\PBR\images\brdfLUT.png
C:\Users\Peter\Desktop\Maya2glTF\Maya\Maya2glTF\PBR\images\damaged_helmet_diffuse_env.dds
C:\Users\Peter\Desktop\Maya2glTF\Maya\Maya2glTF\PBR\images\damaged_helmet_specular_env.dds
C:\Users\Peter\Desktop\Maya2glTF\Maya\Maya2glTF\PBR\shaders\glTF_PBR.ogsfx
```

How did you unpack the ZIP file? 

Could you show me the full directory structure of the unpacked ZIP?

**Comment by krz9000** [comment] 2018-05-29 08:54
will do later tonight once home. thx for looking into it

**Comment by Ziriax** [comment] 2018-05-30 18:41
Closing this since we can't reproduce this, I think the ZIP package was incorrectly extracted.

**Closed by Ziriax** 2018-05-30 18:41 UTC
